import React,{useEffect,useRef,useState}from'react';
import Hls from'hls.js';
import dashjs from'dashjs';
import{Play,Pause,Upload,Maximize,PictureInPicture,Settings,Activity,Repeat2,Camera,History,Trash2,Link2,Code2,Info,Subtitles,Sun,Moon,Volume2,Film,Sparkles,Download,Languages}from'lucide-react';
import SitePage from './pages.jsx';

const API_BASE=(import.meta.env.VITE_API_BASE_URL||'https://streamvg-web-production.up.railway.app').replace(/\/$/,'');
const HIST='streamvg-history';
const clock=s=>{if(!Number.isFinite(s))return'0:00';const h=Math.floor(s/3600),m=Math.floor(s%3600/60),x=Math.floor(s%60);return(h?String(h).padStart(2,'0')+':':'')+String(m).padStart(2,'0')+':'+String(x).padStart(2,'0')};
const isYouTube=u=>{try{const h=new URL(u).hostname.toLowerCase();return ['youtube.com','www.youtube.com','m.youtube.com','youtu.be','www.youtu.be'].includes(h)}catch{return false}};const youtubeEmbed=u=>{try{const x=new URL(u);let id=x.hostname.includes('youtu.be')?x.pathname.slice(1):x.searchParams.get('v');if(!id&&x.pathname.startsWith('/shorts/'))id=x.pathname.split('/')[2];return id?'https://www.youtube.com/embed/'+id+'?autoplay=1&rel=0&playsinline=1':''}catch{return ''}};const escUrl=u=>API_BASE+'/api/proxy?url='+encodeURIComponent(u);const teraHosts=['terabox.com','terabox.app','teraboxshare.com','teraboxlink.com','teraboxurl.com','teraboxapp.com','terabox.club','terabox.link','teraboxfree.com','terafileshare.com','terasharefile.com','terasharelink.com','terashareus.com','1024terabox.com','1024tera.com','1024-terabox.com','tera1024box.com','momerybox.com','bestclouddrive.com','4funbox.in','4funbox.com','mirrobox.com','nephobox.com','pebibox.com','fancybox.in','gibibox.com','tibibox.com'];const isTeraBox=u=>{try{const h=new URL(u).hostname.toLowerCase().replace(/^www\\./,'');return teraHosts.includes(h)||h.includes('terabox')||h.includes('terashare')}catch{return false}};const resolveTeraBox=async u=>{const api='https://terabox-worker.robinkumarshakya103.workers.dev/api?url='+encodeURIComponent(u);const r=await fetch(api);if(!r.ok)throw new Error('TeraBox resolver unavailable');const d=await r.json();const f=(d.files||[]).find(x=>x.streaming_url||x.download_url||x.original_download_url);if(!f)throw new Error('No TeraBox video found');return f.streaming_url||f.download_url||f.original_download_url};

export default function App(){
 const video=useRef(null),file=useRef(null),subFile=useRef(null),hls=useRef(null),dash=useRef(null),sleepTimer=useRef(null);
 const [url,setUrl]=useState(new URLSearchParams(location.search).get('url')||'');
 const [source,setSource]=useState(''),[engine,setEngine]=useState(''),[playing,setPlaying]=useState(false),[resolving,setResolving]=useState(false);
 const [time,setTime]=useState(0),[duration,setDuration]=useState(0),[levels,setLevels]=useState([]),[level,setLevel]=useState(-1);
 const [proxy,setProxy]=useState(false),[speed,setSpeed]=useState(1),[loop,setLoop]=useState({a:null,b:null}),[embedSrc,setEmbedSrc]=useState('');
 const [sleep,setSleep]=useState('Off'),[subtitle,setSubtitle]=useState(''),[tab,setTab]=useState('share'),[codeType,setCodeType]=useState('iframe'),[theater,setTheater]=useState(false),[cinema,setCinema]=useState(false),[ambient,setAmbient]=useState(false),[theaterRatio,setTheaterRatio]=useState('16/9'),[dark,setDark]=useState(true),[audioTracks,setAudioTracks]=useState([]),[audioTrack,setAudioTrack]=useState(-1),[captionTracks,setCaptionTracks]=useState([]),[captionTrack,setCaptionTrack]=useState(-1);
 const [history,setHistory]=useState(()=>{try{return JSON.parse(localStorage.getItem(HIST)||'[]')}catch{return[]}});
 const [stats,setStats]=useState({resolution:'—',bitrate:'—',bandwidth:'—',buffer:'0.0s',dropped:0,codec:'—'});
 const [resume,setResume]=useState(null);

 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light'},[dark]);
 useEffect(()=>{const v=video.current;if(!v)return;
  const timeUpdate=()=>{setTime(v.currentTime);if(source)localStorage.setItem('streamvg-pos-'+source,String(v.currentTime));if(loop.a!=null&&loop.b!=null&&v.currentTime>=loop.b)v.currentTime=loop.a};
  const meta=()=>setDuration(v.duration||0);const play=()=>setPlaying(true);const pause=()=>setPlaying(false);
  v.addEventListener('timeupdate',timeUpdate);v.addEventListener('loadedmetadata',meta);v.addEventListener('play',play);v.addEventListener('pause',pause);
  return()=>{v.removeEventListener('timeupdate',timeUpdate);v.removeEventListener('loadedmetadata',meta);v.removeEventListener('play',play);v.removeEventListener('pause',pause)}
 },[source,loop]);
 useEffect(()=>{const id=setInterval(()=>{const v=video.current;if(!v)return;let b=0;if(v.buffered.length)b=Math.max(0,v.buffered.end(v.buffered.length-1)-v.currentTime);const q=v.getVideoPlaybackQuality?.();setStats(s=>({...s,buffer:b.toFixed(1)+'s',dropped:q?.droppedVideoFrames??s.dropped,resolution:v.videoWidth?(v.videoWidth+'×'+v.videoHeight):s.resolution}))},1000);return()=>clearInterval(id)},[]);

 const destroy=()=>{hls.current?.destroy();hls.current=null;if(dash.current){try{dash.current.reset()}catch{}}dash.current=null;setLevels([]);setAudioTracks([]);setAudioTrack(-1);setCaptionTracks([]);setCaptionTrack(-1)};
 const addHistory=u=>{let h=[{url:u,host:new URL(u).host,title:u.split('/').pop()||u,at:Date.now()},...history.filter(x=>x.url!==u)].slice(0,15);setHistory(h);localStorage.setItem(HIST,JSON.stringify(h))};

 const resolveUrl=async input=>{const direct=/\.(m3u8|mpd|mp4|webm|m4v|mov|ogv|ogg|mkv|ts)(?:[?#]|$)/i.test(input);if(direct)return input;setResolving(true);try{let current=input;const seen=new Set();for(let depth=0;depth<6;depth++){if(seen.has(current))break;seen.add(current);const r=await fetch(API_BASE+'/api/resolve?url='+encodeURIComponent(current));const d=await r.json();if(d.kind==='media'&&d.url)return d.url;const next=[...(d.links||[]),...(d.iframes||[])].find(x=>x&&!seen.has(x));if(!next)break;current=next}throw new Error('No playable media found')}finally{setResolving(false)}};
 const load=async(input=url,fromHistory=false)=>{
  if(!input)return;try{new URL(input)}catch{alert('Please enter a valid video URL.');return}
  const original=input;let playable=input;setEmbedSrc('');
  if(isYouTube(input)){const e=youtubeEmbed(input);if(e){destroy();setSource(original);setLevels([]);setLevel(-1);setResume(null);setEmbedSrc(e);setEngine('YouTube Player');if(!fromHistory)addHistory(original);window.history.pushState({},'', '?url='+encodeURIComponent(original));return}}
  if(isTeraBox(input)){try{playable=await resolveUrl(input)}catch{setEngine('TeraBox • No playable media found');alert('StreamVG could not resolve this TeraBox video.');return}}else{try{playable=await resolveUrl(input)}catch{setEngine('Resolver • No playable media found');alert('StreamVG could not find a playable video from this URL.');return}}
  destroy();setSource(original);setLevels([]);setLevel(-1);setResume(null);
  const v=video.current;const actual=proxy?escUrl(playable):playable;const low=playable.toLowerCase();
  if(low.includes('.m3u8')){
   setEngine('HLS.js');
   if(Hls.isSupported()){const x=new Hls({enableWorker:true});hls.current=x;
    x.on(Hls.Events.MANIFEST_PARSED,(_,d)=>{setLevels(d.levels.map((l,i)=>({i,height:l.height,width:l.width,bitrate:l.bitrate,codec:l.videoCodec||l.codecs||'—'})));setAudioTracks((x.audioTracks||[]).map((t,i)=>({i,label:t.name||t.lang||('Audio '+(i+1)),lang:t.lang||''})));setCaptionTracks((x.subtitleTracks||[]).map((t,i)=>({i,label:t.name||t.lang||('Subtitle '+(i+1)),lang:t.lang||''})))});
    x.on(Hls.Events.LEVEL_SWITCHED,(_,d)=>{const l=x.levels[d.level];setLevel(d.level);setStats(s=>({...s,resolution:l?.width?(l.width+'×'+l.height):s.resolution,bitrate:l?.bitrate?((l.bitrate/1000000).toFixed(2)+' Mbps'):s.bitrate,bandwidth:x.bandwidthEstimate?((x.bandwidthEstimate/1000000).toFixed(2)+' Mbps'):s.bandwidth,codec:l?.videoCodec||l?.codecs||s.codec}))});
    x.loadSource(actual);x.attachMedia(v);
   }else if(v.canPlayType('application/vnd.apple.mpegurl'))v.src=actual;else{alert('HLS is not supported by this browser.');return}
  }else if(low.includes('.mpd')){
   setEngine('DASH.js');
   const d=dashjs.MediaPlayer().create();dash.current=d;
   const readDash=()=>{try{
    const reps=d.getRepresentationsByTypeUnfiltered?.('video')||d.getRepresentationsByType('video')||[];
    setLevels(reps.map((r,i)=>({i,height:r.height,width:r.width,bitrate:r.bitrateInKbit?Math.round(r.bitrateInKbit*1000):(r.bandwidth||0),codec:r.codecs||r.codec||'—'})));
    const cur=d.getCurrentRepresentationForType('video');
    if(cur){const i=reps.findIndex(r=>r.id===cur.id);setLevel(i>=0?i:-1);setStats(s=>({...s,resolution:cur.width&&cur.height?(cur.width+'×'+cur.height):s.resolution,bitrate:cur.bitrateInKbit?((cur.bitrateInKbit/1000).toFixed(2)+' Mbps'):cur.bandwidth?((cur.bandwidth/1000000).toFixed(2)+' Mbps'):s.bitrate,codec:cur.codecs||cur.codec||s.codec}))}
   }catch(err){console.error('DASH representation read error',err)}};
   const onDashReady=()=>{readDash();try{const ats=d.getTracksFor?.('audio')||[];setAudioTracks(ats.map((t,i)=>({i,label:t.lang||t.id||('Audio '+(i+1)),lang:t.lang||''})))}catch{}try{const sts=d.getTracksFor?.('text')||[];setCaptionTracks(sts.map((t,i)=>({i,label:t.lang||t.id||('Subtitle '+(i+1)),lang:t.lang||''})))}catch{}setTimeout(readDash,500);setTimeout(()=>v.play().catch(()=>{}),0)};
   d.on(dashjs.MediaPlayer.events.STREAM_INITIALIZED,onDashReady);
   d.on(dashjs.MediaPlayer.events.QUALITY_CHANGE_RENDERED,()=>{readDash()});
   d.on(dashjs.MediaPlayer.events.ERROR,e=>{console.error('DASH error',e);setEngine('DASH.js • Error')});
   try{d.initialize(v,actual,false)}catch(err){console.error(err);setEngine('DASH.js • Error');alert('DASH could not be loaded. The stream may be unsupported or unavailable.')}
  }else{setEngine(input.startsWith('blob:')?'HTML5 Local':'HTML5 Native');v.src=actual;v.play().catch(()=>{})}
  if(!original.startsWith('blob:'))addHistory(original);
  if(!fromHistory){const p=Number(localStorage.getItem('streamvg-pos-'+input)||0);if(p>5)setResume(p)}
  window.history.pushState({},'',original.startsWith('blob:')?location.pathname:'?url='+encodeURIComponent(original));
 };

 const localPlay=f=>{if(!f)return;destroy();const u=URL.createObjectURL(f);setUrl('');setSource(u);setEngine('HTML5 Local');video.current.src=u;video.current.play().catch(()=>{})};
 const addSubtitle=f=>{if(!f)return;const r=new FileReader();r.onload=()=>{let t=String(r.result).replace(/\r/g,'');if(f.name.toLowerCase().endsWith('.srt')){t='WEBVTT\\n\\n'+t.replace(/(\\d{2}:\\d{2}:\\d{2}),(\\d{3})/g,'$1.$2').replace(/^\\d+\\s*\\n/gm,'')}const b=new Blob([t],{type:'text/vtt'});setSubtitle(URL.createObjectURL(b))};r.readAsText(f)};
 const screenshot=()=>{const v=video.current;if(!v.videoWidth)return;const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);const a=document.createElement('a');a.href=c.toDataURL('image/png');a.download='streamvg-screenshot.png';a.click()};
 const sleepChange=x=>{setSleep(x);clearTimeout(sleepTimer.current);if(x==='Custom'){const m=Number(prompt('Sleep timer minutes:', '90'));if(Number.isFinite(m)&&m>0)sleepTimer.current=setTimeout(()=>video.current?.pause(),m*60000);return}if(x!=='Off')sleepTimer.current=setTimeout(()=>video.current?.pause(),Number(x)*60000)};
 const changeAudio=i=>{const x=Number(i);setAudioTrack(x);if(hls.current){hls.current.audioTrack=x}else if(dash.current){try{const ts=dash.current.getTracksFor?.('audio')||[];if(ts[x])dash.current.setCurrentTrack?.(ts[x])}catch{}}};
 const changeCaption=i=>{const x=Number(i);setCaptionTrack(x);if(hls.current){hls.current.subtitleTrack=x}else if(dash.current){try{const ts=dash.current.getTracksFor?.('text')||[];if(ts[x])dash.current.setCurrentTrack?.(ts[x])}catch{}}};
 const downloadVideo=()=>{if(!source)return;window.location.href='https://vgsave.pages.dev/?url='+encodeURIComponent(source)};
 const codeSnippet=()=>{if(!source)return'Play a stream first.';if(codeType==='iframe')return '<iframe src="'+share+'" width="100%" height="500" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>';if(codeType==='hls')return "const video = document.querySelector('video');\\nconst hls = new Hls();\\nhls.loadSource('"+source.replace(/'/g,"\\\\'")+"');\\nhls.attachMedia(video);";if(codeType==='videojs')return "const player = videojs('streamvg-video');\\nplayer.src({src: '"+source.replace(/'/g,"\\\\'")+"', type: '"+(source.toLowerCase().includes('.m3u8')?'application/x-mpegURL':source.toLowerCase().includes('.mpd')?'application/dash+xml':'video/mp4')+"'});";return 'ffprobe -hide_banner "'+source+'"\\nffmpeg -i "'+source+'" -c copy output.mp4'};
 const share=location.origin+'/?url='+encodeURIComponent(source);

 return <div className="app">
  <header><div className="brand"><span>SV</span><div><b>StreamVG</b><small>PLAY • ANALYZE • EXPERIENCE</small></div></div><div className="headerPulse"><i/> LIVE ENGINE <b>READY</b></div><div className="headerActions"><button className="headerChip" onClick={()=>setAmbient(!ambient)}><Sparkles/> Ambient</button><button className="icon" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button></div></header>
  <main>
   <section className="hero"><div className="heroGrid" aria-hidden="true"><span/><span/><span/></div><div className="eyebrow"><i/> THE WEB'S CINEMA <b>v2.0</b></div><h1>Turn any URL into<br/><em>a cinema.</em></h1><p>Paste a video page, stream, TeraBox link or direct media URL. StreamVG resolves what the source exposes and gives you a full control room around it.</p>
    <div className="inputRow"><input value={url} onChange={e=>setUrl(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Paste any video URL — page, Telegram, TeraBox, MP4, HLS or DASH"/><button className="primary" onClick={()=>load()} disabled={resolving}><Play/> {resolving?'Finding video…':'Play'}</button><button className="secondary" onClick={()=>file.current?.click()}><Upload/> Local</button><input ref={file} hidden type="file" accept="video/*" onChange={e=>localPlay(e.target.files[0])}/></div>
    <div className="heroMeta"><label className="toggle"><input type="checkbox" checked={proxy} onChange={e=>setProxy(e.target.checked)}/><span/>Use CORS proxy</label><span>↵ Enter to play</span><span>16× speed</span><span>HLS + DASH</span></div><div className="quickLaunch"><button onClick={()=>setUrl('')}><span>⌘</span> New stream</button><button onClick={()=>setTab('history')}><History/> Recent streams</button><button onClick={()=>setCinema(true)}><Film/> Cinema instantly</button><button onClick={()=>setTheater(true)}><Activity/> Enter theatre</button></div>
   </section>
   <section className={'playerCard'+(theater?' theater':'')+(cinema?' cinemaMode':'')+(ambient?' ambientOn':'')}><div className="playerTopbar"><span className="nowDot"/><b>{engine||'STREAMVG PLAYER'}</b><span>{source?'SOURCE CONNECTED':'WAITING FOR A URL'}</span><div className="playerTopActions"><button onClick={()=>setCinema(!cinema)}>{cinema?'Exit cinema':'Cinema'}</button><button onClick={()=>setTheater(!theater)}>{theater?'Exit theatre':'Theatre'}</button>{theater&&<label className="theatreRatio">Screen <select value={theaterRatio} onChange={e=>setTheaterRatio(e.target.value)}><option value="16/9">16:9</option><option value="21/9">21:9</option><option value="2.39/1">2.39:1</option><option value="4/3">4:3</option><option value="1/1">1:1</option></select></label>}</div></div><div className="ambientGlow" aria-hidden="true"/>{theater&&<div className="theatreAtmosphere" aria-hidden="true"><div className="theatreHeader"><span>LIVE THEATRE</span><b>SCREEN 01</b><span>● HOUSE LIGHTS</span></div><div className="curtain curtainLeft"/><div className="curtain curtainRight"/><div className="stageGlow"/><div className="seatRows">{[0,1,2,3,4].map(r=><div className="seatRow" key={r}>{Array.from({length:9}).map((_,i)=><i key={i}/>)}</div>)}</div><div className="aisle"/></div>}<div className="videoWrap" style={theater?{aspectRatio:theaterRatio}:undefined}>{embedSrc?<iframe src={embedSrc} title="StreamVG video" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowFullScreen style={{width:'100%',height:'100%',border:0}}/>:<video ref={video} controls playsInline referrerPolicy="no-referrer">{subtitle&&<track kind="subtitles" src={subtitle} default/>}</video>}</div>
    <div className="controls"><button onClick={()=>playing?video.current.pause():video.current.play()}>{playing?<Pause/>:<Play/>}</button><span>{clock(time)} / {clock(duration)}</span><input className="seek" type="range" min="0" max={duration||0} step=".1" value={time} onChange={e=>video.current.currentTime=Number(e.target.value)}/><select value={speed} onChange={e=>{let x=Number(e.target.value);setSpeed(x);video.current.playbackRate=x}}>{[.25,.5,.75,1,1.25,1.5,2,4,8,16].map(x=><option key={x} value={x}>{x}×</option>)}</select><button onClick={screenshot}><Camera/></button><button onClick={()=>video.current.requestPictureInPicture?.()}><PictureInPicture/></button><button onClick={()=>video.current.requestFullscreen?.()}><Maximize/></button><button className={cinema?"modeActive":""} onClick={()=>{setCinema(!cinema);if(!cinema)setTheater(false)}} title="Cinema Mode — clean immersive"><Film/></button><button className={theater?"modeActive":""} onClick={()=>{setTheater(!theater);if(!theater)setCinema(false)}} title="Theatre Mode — virtual auditorium"><Activity/></button><button className={ambient?"modeActive":""} onClick={()=>setAmbient(!ambient)} title="Ambient Mode — live color glow"><Sparkles/></button></div>
   </section>
   {resume!=null&&<div className="resume">Resume from {clock(resume)}? <button onClick={()=>{video.current.currentTime=resume;setResume(null)}}>Resume</button><button onClick={()=>setResume(null)}>Dismiss</button></div>}
   <section className="grid">
    <div className="panel"><div className="panelHead"><h2><Settings/> Quality & Tools</h2><span>{levels.length?'Adaptive quality available':'Source-dependent controls'}</span><span>{engine||'Waiting'}</span></div>
     <select value={level} onChange={e=>{let x=Number(e.target.value);setLevel(x);if(hls.current)hls.current.currentLevel=x;else if(dash.current){try{if(x<0)dash.current.updateSettings({streaming:{abr:{autoSwitchBitrate:{video:true}}}});else{dash.current.updateSettings({streaming:{abr:{autoSwitchBitrate:{video:false}}}});dash.current.setRepresentationForTypeByIndex('video',x,true)}}catch(err){console.error(err)}}}}><option value="-1">Auto (ABR)</option>{levels.map(l=><option key={l.i} value={l.i}>{l.height?l.height+'p':'Unknown'}{l.bitrate?' — '+(l.bitrate/1000000).toFixed(2)+' Mbps':''}</option>)}</select>
     <div className="tools"><button className="downloadBtn" onClick={downloadVideo}><Download/> Download</button><button onClick={()=>setLoop({...loop,a:time})}><Repeat2/> Set A</button><button onClick={()=>setLoop({...loop,b:time})}>Set B</button><button onClick={()=>setLoop({a:null,b:null})}>Clear Loop</button></div>
     <div className="tools"><select value={audioTrack} onChange={e=>changeAudio(e.target.value)} disabled={!audioTracks.length}><option value="-1">Audio: Auto</option>{audioTracks.map(t=><option key={t.i} value={t.i}>{t.label}{t.lang?' · '+t.lang:''}</option>)}</select><select value={captionTrack} onChange={e=>changeCaption(e.target.value)} disabled={!captionTracks.length}><option value="-1">Subtitles: Off</option>{captionTracks.map(t=><option key={t.i} value={t.i}>{t.label}{t.lang?' · '+t.lang:''}</option>)}</select><select value={sleep} onChange={e=>sleepChange(e.target.value)}><option>Off</option><option value="15">Sleep 15m</option><option value="30">Sleep 30m</option><option value="60">Sleep 60m</option><option value="Custom">Custom…</option></select><button onClick={()=>subFile.current?.click()}><Subtitles/> Add subtitles</button><input ref={subFile} hidden type="file" accept=".srt,.vtt" onChange={e=>addSubtitle(e.target.files[0])}/></div>
    </div>
    <div className="panel"><div className="panelHead"><h2><Activity/> Live Diagnostics</h2></div><div className="stats">{[['resolution','Resolution'],['bitrate','Bitrate'],['bandwidth','Bandwidth'],['buffer','Buffer'],['dropped','Dropped frames'],['codec','Codec']].map(a=><div key={a[0]}><b>{stats[a[0]]}</b><small>{a[1]}</small></div>)}</div></div>
   </section>
   <section className="panel wide"><div className="tabs"><button className={tab==='share'?'active':''} onClick={()=>setTab('share')}><Link2/> Share</button><button className={tab==='code'?'active':''} onClick={()=>setTab('code')}><Code2/> Embed</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}><History/> History</button></div>
    {tab==='share'&&<div className="shareBox"><input readOnly value={source?share:''}/><button onClick={()=>source&&navigator.clipboard?.writeText(share)}>Copy</button></div>}
    {tab==='code'&&<div className="codeTools"><div className="codeTabs"><button className={codeType==='iframe'?'active':''} onClick={()=>setCodeType('iframe')}>iFrame</button><button className={codeType==='hls'?'active':''} onClick={()=>setCodeType('hls')}>HLS.js</button><button className={codeType==='videojs'?'active':''} onClick={()=>setCodeType('videojs')}>Video.js</button><button className={codeType==='ffmpeg'?'active':''} onClick={()=>setCodeType('ffmpeg')}>FFmpeg</button></div><div className="codeActions"><button onClick={()=>navigator.clipboard?.writeText(codeSnippet())}>Copy code</button></div><pre>{codeSnippet()}</pre></div>}
    {tab==='history'&&<div className="history">{history.length?history.map(x=><button className="historyItem" key={x.url} onClick={()=>{setUrl(x.url);load(x.url,true)}}><b>{x.host}</b><small>{x.url}</small></button>):<p>No recent streams.</p>}<button className="danger" onClick={()=>{setHistory([]);localStorage.removeItem(HIST)}}><Trash2/> Clear history</button></div>}
   </section>
   <section className="featureBento"><div className="bentoIntro"><span className="eyebrow"><i/> CONTROL ROOM</span><h2>More than a player.</h2><p>Built for people who actually care about the way a video feels.</p></div><button className="bentoCard glowCard" onClick={()=>setAmbient(!ambient)}><Sparkles/><b>Ambient Flow</b><small>Living color around the screen</small><span className="cardArrow">↗</span></button><button className="bentoCard" onClick={()=>setCinema(true)}><Film/><b>Cinema Mode</b><small>Ultra-wide, distraction-free viewing</small><span className="cardArrow">↗</span></button><button className="bentoCard theatreCard" onClick={()=>setTheater(true)}><Activity/><b>Live Theatre</b><small>Screen, curtains, seats & house atmosphere</small><span className="cardArrow">↗</span></button><button className="bentoCard" onClick={()=>setTab('share')}><Link2/><b>Instant Share</b><small>Send a ready-to-play StreamVG link</small><span className="cardArrow">↗</span></button></section><div className="featureStrip"><span><Sparkles/> Ambient</span><span><Film/> Cinema Mode</span><span><Activity/> Live Theatre</span><span><Volume2/> Multi-audio</span><span><Languages/> Subtitles</span><span><Download/> VGSAVE download</span></div><div className="info"><Info/><div><b>About StreamVG</b><p>StreamVG accepts URLs without requiring them to be labeled public. It can only play media that the supplied URL and its available access actually expose; DRM or missing authentication cannot be unlocked by the player.</p></div></div>
  </main><footer>StreamVG • Free web video player • Use media you have permission to access.<nav><a href="/about/">About</a><a href="/faq/">FAQ</a><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a><a href="/copyright/">Copyright</a><a href="/contact/">Contact</a></nav></footer>
 </div>
}